# Cross-compilation configuration for CacheKill
# This file configures cargo to use cross-compilation targets

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin-gcc"

# Build configuration
[build]
# Use release profile for better performance
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-s",  # Strip symbols for smaller binaries
]

# Profile configuration for release builds
[profile.release]
# Optimize for size and speed
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
