# Cross-compilation configuration for Cache Kill
# This file configures cargo for cross-compilation when needed

# Only apply cross-compilation settings when explicitly targeting those platforms
# These settings are used by GitHub Actions for cross-compilation

# Profile configuration for release builds
[profile.release]
# Optimize for size and speed
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
