name: CI

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      RUSTFLAGS: -C debuginfo=0
      CARGO_PROFILE_RELEASE_LTO: 'false'
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: '16'
      CARGO_PROFILE_RELEASE_OPT_LEVEL: '2'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Enable sccache
        uses: mozilla-actions/sccache-action@v0.0.6

      - name: Configure sccache env
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          sccache --version

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2

      - name: Run tests (bin cachekill)
        run: cargo test --verbose --locked --bin cachekill

      - name: Run clippy
        run: cargo clippy

      - name: Check formatting
        run: cargo fmt -- --check

  build-check:
    name: Build Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2

      - name: Build (bin cachekill)
        run: cargo build --release --locked --bin cachekill

      - name: Test binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          ./target/release/cachekill --version
          ./target/release/mcp --version

      - name: Test binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          ./target/release/cachekill.exe --version
          ./target/release/mcp.exe --version
